addpath('../src');
clear;

GRAD_HSPACE = 1e-14;


init = 2;

cparams = struct( ...
    'maxiter',          100, ...
    'eps',              1e-5,   ...
    'hspace',           1e-10, ...
    'line_search_eps',  1e-10, ...
    'line_search_beta', 0.7 ...
);

[opt, log] = optim.gd(@rectangle_fun, init, cparams);