clear;clc;addpath('../src');

diary('test_optimization_diary.txt');



init_weight = [1];


% Gradient descent parameter
gd_params = struct( ...
    'maxiter',          100, ...
    'report',           1, ...
    'eps',              1e-6,   ...
    'hspace',           1e-3, ...
    'line_search_eps',  1e-6, ...
    'line_search_beta', 0.5 ...
)

loss_params = struct(...
    'default_chebabs',      [1 8], ...
    'chnk_fun',             @chnk_rectangle, ...
    'udnorm_ord',              'inf', ...
    'unorm_ord',                  '2' ...
)


fprintf('Rectangle optimization\n');
[opt, gd_log] = gd(@loss, init_weight, gd_params, loss_params);
fprintf('optimal weight: %5.2e \n', opt);
fprintf('optimal value: %5.2e \n', fun(opt));
clear fun


diary off;