addpath('../src');
clear;
clc;


cparams = struct( ...
    'maxiter',          10, ...
    'report',           1, ...
    'eps',              1e-2,   ...
    'hspace',           1e-3, ...
    'line_search_eps',  1e-3, ...
    'line_search_beta', 0.7 ...
);


init_weight = 1.5;
fun = @rect_loss;
[opt, gd_log] = optim.gd(fun, init_weight, cparams);
fprintf('optimal weight: %5.2e \n', opt);
fprintf('optimal value: %5.2e \n', fun(opt));
clear fun
