clear;clc;addpath('../src');

% Case 1: square side length 1 alpha = 1
rs = ones(1,4)/sqrt(2);
alpha = 1;
plot(chnk_poly(rs))
loss_params = struct(...
'default_chebabs',      [4 5], ...
'chnk_fun',             @chnk_poly, ...
'udnorm_ord',              '3', ...
'unorm_ord',                  '2' ...
);
loss_computed = loss(rs, loss_params)

loss_params = struct(...
'default_chebabs',      [2 6], ...
'chnk_fun',             @chnk_poly, ...
'udnorm_ord',              '3', ...
'unorm_ord',                  '2' ...
);
loss_true = rect_true_loss(alpha, loss_params)